import { describe, it, expect, vi } from 'vitest';
import { processRawText } from '../../data/3_pipeline/processor';
import { llmClient } from '../../data/3_pipeline/llmClient';

// Mock the LLM client
vi.mock('../../data/3_pipeline/llmClient', () => ({
  llmClient: {
    generateJson: vi.fn(),
  },
}));

describe('Data Processing Utility', () => {
  it('should process raw text and return structured data based on LLM output', async () => {
    const rawText = "Alex is a great collaborator and shows strong leadership.";
    const sourcePath = "data/1_raw/recommendations/test.txt";

    const mockLlmResponse = {
      evidence: {
        id: 'evidence-llm-123',
        source: 'recommendation',
        text: rawText,
        author: 'LLM-Generated',
      },
      concepts: [
        { id: 'concept-llm-456', label: 'collaboration', sourceEvidenceIds: ['evidence-llm-123'] },
        { id: 'concept-llm-789', label: 'leadership', sourceEvidenceIds: ['evidence-llm-123'] },
      ],
    };

    // Configure the mock to return the predefined response
    (llmClient.generateJson as vi.Mock).mockResolvedValue(mockLlmResponse);

    const result = await processRawText(rawText, sourcePath);

    // Assert that the processor function returns the data as expected, allowing for a dynamic ID
    expect(result.evidence.id).toEqual(expect.any(String));
    expect(result.evidence.text).toEqual(mockLlmResponse.evidence.text);
    expect(result.concepts).toEqual(mockLlmResponse.concepts);
    
    // Assert that the LLM client was called correctly
    expect(llmClient.generateJson).toHaveBeenCalledWith(rawText, expect.any(String));
  });

  it('should generate a unique evidence ID in the code, ignoring the LLM ID', async () => {
    const rawText = "Some text.";
    const sourcePath = "data/1_raw/test.txt";
    
    const mockLlmResponse = {
      evidence: {
        id: 'llm-generated-id', // This ID should be ignored
        source: 'Test',
        text: rawText,
        author: 'Test Author',
      },
      concepts: [],
    };

    (llmClient.generateJson as vi.Mock).mockResolvedValue(JSON.parse(JSON.stringify(mockLlmResponse)));

    // Call the function twice
    const result1 = await processRawText(rawText, sourcePath);
    const result2 = await processRawText(rawText, sourcePath);

    // Assert that the IDs were generated by our code and are unique
    expect(result1.evidence.id).not.toEqual('llm-generated-id');
    expect(result2.evidence.id).not.toEqual('llm-generated-id');
    expect(result1.evidence.id).not.toEqual(result2.evidence.id);
  });
});
